---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Actualizar caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar programas
      apt:
        name:
          - curl
          - git
        state: present

    - name: Instalar Brew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Instalar Tailscale
      shell: curl -fsSL https://tailscale.com/install.sh | sh

    - name: Instalar k3s
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Instalar k9s
      shell: curl -LO "https://github.com/derailed/k9s/releases/download/v0.24.7/k9s_Linux_x86_64.tar.gz"
             tar xf k9s_Linux_x86_64.tar.gz
             sudo mv k9s /usr/local/bin/

