version: "2.1"
services:
  esphome:
    image: esphome/esphome:latest
    container_name: esphome
    volumes:
      - esphome-data:/config
    ports:
      - 6052:6052 #optional
    restart: unless-stopped
volumes:
  esphome-data: